# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

# Install necessary system packages
RUN apk add --no-cache build-base postgresql-dev

# Set working directory
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose any necessary port if applicable (not needed for stdio transport)

# Set the entrypoint
CMD [ "python", "server.py" ]
